<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Product>XIVLauncher.Accounts</Product>
        <AssemblyTitle>XIVLauncher.Accounts</AssemblyTitle>
        <Description>Login device profiles for XIVLauncher.</Description>
        <VersionPrefix>1.0.0</VersionPrefix>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>

        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    </PropertyGroup>
</Project>
