<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="goaaats.Steamworks" Version="2.3.4" />
    <PackageVersion Include="Avalonia.X11" Version="11.3.22" />
    <PackageVersion Include="Avalonia.Skia" Version="11.3.22" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageVersion Include="Downloader" Version="5.9.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="SharpCompress" Version="0.49.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
  </ItemGroup>
</Project>